//package panel.bill;
package rs.np.storage_manager_client.panel.bill;

import com.toedter.calendar.JDateChooser;
import javax.accessibility.AccessibleContext;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.event.EventListenerList;
import javax.swing.plaf.ComponentUI;
//import panel.note.*;

/**
 *
 * @author Milan
 */
public class BillOfLadingPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 8228608001105307856L;

	/**
     * Creates new form GoodsReceivedNotePanel
     */
    public BillOfLadingPanel() {
        initComponents();
        preparePanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNoteID = new javax.swing.JLabel();
        lblGoodsReceivedNote = new javax.swing.JLabel();
        lblTotalCost = new javax.swing.JLabel();
        txtCost = new javax.swing.JTextField();
        lblNoteID1 = new javax.swing.JLabel();
        lblPick = new javax.swing.JLabel();
        lblLegalPerson = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNoteID = new javax.swing.JTextField();
        cbFirms = new javax.swing.JComboBox<>();
        cbLegalPersons = new javax.swing.JComboBox<>();
        IssueDateChooser = new com.toedter.calendar.JDateChooser();
        dueDateChooser = new com.toedter.calendar.JDateChooser();
        btnSwitch = new javax.swing.JButton();
        lblNaturalPerson = new javax.swing.JLabel();
        cbNaturalPersons = new javax.swing.JComboBox<>();

        lblNoteID.setText("ID:");

        lblGoodsReceivedNote.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGoodsReceivedNote.setText("BILL OF LADING:");

        lblTotalCost.setText("Total Price:");

        lblNoteID1.setText("ID:");

        lblPick.setText("Pick your firm:");

        lblLegalPerson.setText("Legal Person:");

        jLabel5.setText("Issue date:");

        jLabel6.setText("Due date:");

        cbFirms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFirmsActionPerformed(evt);
            }
        });

        btnSwitch.setText("Switch Buyer Mode");
        btnSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwitchActionPerformed(evt);
            }
        });

        lblNaturalPerson.setText("Natural Person:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGoodsReceivedNote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                        .addComponent(lblTotalCost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbLegalPersons, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40)
                        .addComponent(btnSwitch)
                        .addGap(40, 40, 40)
                        .addComponent(cbNaturalPersons, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblNoteID1)
                        .addGap(69, 69, 69)
                        .addComponent(txtNoteID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPick)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFirms, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IssueDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dueDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLegalPerson)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNaturalPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGoodsReceivedNote)
                    .addComponent(lblTotalCost)
                    .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoteID1)
                    .addComponent(txtNoteID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFirms, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPick))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLegalPerson)
                    .addComponent(lblNaturalPerson))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLegalPersons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSwitch)
                    .addComponent(cbNaturalPersons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(IssueDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(dueDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbFirmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFirmsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFirmsActionPerformed

    private void btnSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwitchActionPerformed
        // TODO add your handling code here:
        if(!getCbNaturalPersons().isEnabled()){
            getCbNaturalPersons().setEnabled(true);
            getCbLegalPersons().setEnabled(false);
        }else {
            getCbNaturalPersons().setEnabled(false);
            getCbLegalPersons().setEnabled(true);
        }
    }//GEN-LAST:event_btnSwitchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser IssueDateChooser;
    private javax.swing.JButton btnSwitch;
    private javax.swing.JComboBox<Object> cbFirms;
    private javax.swing.JComboBox<Object> cbLegalPersons;
    private javax.swing.JComboBox<Object> cbNaturalPersons;
    private com.toedter.calendar.JDateChooser dueDateChooser;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblGoodsReceivedNote;
    private javax.swing.JLabel lblLegalPerson;
    private javax.swing.JLabel lblNaturalPerson;
    private javax.swing.JLabel lblNoteID;
    private javax.swing.JLabel lblNoteID1;
    private javax.swing.JLabel lblPick;
    private javax.swing.JLabel lblTotalCost;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtNoteID;
    // End of variables declaration//GEN-END:variables

    private void preparePanel() {
        getCbNaturalPersons().setEnabled(false);
    }

    public JDateChooser getIssueDateChooser() {
        return IssueDateChooser;
    }

    public void setIssueDateChooser(JDateChooser IssueDateChooser) {
        this.IssueDateChooser = IssueDateChooser;
    }

    public JButton getBtnSwitch() {
        return btnSwitch;
    }

    public void setBtnSwitch(JButton btnSwitch) {
        this.btnSwitch = btnSwitch;
    }

    public JComboBox<Object> getCbFirms() {
        return cbFirms;
    }

    public void setCbFirms(JComboBox<Object> cbFirms) {
        this.cbFirms = cbFirms;
    }

    public JComboBox<Object> getCbLegalPersons() {
        return cbLegalPersons;
    }

    public void setCbLegalPersons(JComboBox<Object> cbLegalPersons) {
        this.cbLegalPersons = cbLegalPersons;
    }

    public JComboBox<Object> getCbNaturalPersons() {
        return cbNaturalPersons;
    }

    public void setCbNaturalPersons(JComboBox<Object> cbNaturalPersons) {
        this.cbNaturalPersons = cbNaturalPersons;
    }

    public JDateChooser getDueDateChooser() {
        return dueDateChooser;
    }

    public void setDueDateChooser(JDateChooser dueDateChooser) {
        this.dueDateChooser = dueDateChooser;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getLblGoodsReceivedNote() {
        return lblGoodsReceivedNote;
    }

    public void setLblGoodsReceivedNote(JLabel lblGoodsReceivedNote) {
        this.lblGoodsReceivedNote = lblGoodsReceivedNote;
    }

    public JLabel getLblLegalPerson() {
        return lblLegalPerson;
    }

    public void setLblLegalPerson(JLabel lblLegalPerson) {
        this.lblLegalPerson = lblLegalPerson;
    }

    public JLabel getLblNaturalPerson() {
        return lblNaturalPerson;
    }

    public void setLblNaturalPerson(JLabel lblNaturalPerson) {
        this.lblNaturalPerson = lblNaturalPerson;
    }

    public JLabel getLblNoteID() {
        return lblNoteID;
    }

    public void setLblNoteID(JLabel lblNoteID) {
        this.lblNoteID = lblNoteID;
    }

    public JLabel getLblNoteID1() {
        return lblNoteID1;
    }

    public void setLblNoteID1(JLabel lblNoteID1) {
        this.lblNoteID1 = lblNoteID1;
    }

    public JLabel getLblPick() {
        return lblPick;
    }

    public void setLblPick(JLabel lblPick) {
        this.lblPick = lblPick;
    }

    public JLabel getLblTotalCost() {
        return lblTotalCost;
    }

    public void setLblTotalCost(JLabel lblTotalCost) {
        this.lblTotalCost = lblTotalCost;
    }

    public JTextField getTxtCost() {
        return txtCost;
    }

    public void setTxtCost(JTextField txtCost) {
        this.txtCost = txtCost;
    }

    public JTextField getTxtNoteID() {
        return txtNoteID;
    }

    public void setTxtNoteID(JTextField txtNoteID) {
        this.txtNoteID = txtNoteID;
    }

    public ComponentUI getUi() {
        return ui;
    }

    public void setUi(ComponentUI ui) {
        this.ui = ui;
    }

    public EventListenerList getListenerList() {
        return listenerList;
    }

    public void setListenerList(EventListenerList listenerList) {
        this.listenerList = listenerList;
    }

    public AccessibleContext getAccessibleContext() {
        return accessibleContext;
    }

    public void setAccessibleContext(AccessibleContext accessibleContext) {
        this.accessibleContext = accessibleContext;
    }
    
}
